name: fit_curve
description: Dart implementation of Philip J. Schneider's \"Algorithm for Automatically Fitting Digitized Curves\" from the book \"Graphics Gems\"
version: 1.0.0
repository: https://github.com/bjartebore/fit_curve

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  lints: ^1.0.1

dev_dependencies:
  pedantic: ^1.10.0
